### PR TITLE
Changed desing and dark mode

### PR DESCRIPTION
**Pull request by xeBuz**
Hi @raicem 

I made a small change in how the page is displayed, I hope it's fine. Also, if the page is blocked on "incognito" it will change the theme to a 'dark' mode.

image

PS: The idea behind the dark mode is to implement it with a extensionSetting, but I can't figure out yet how to provide the setting value on `redirectToBlockedPage`

### CODE REVIEW

**Comment by xeBuz** [comment]
ping @raicem

**Comment by raicem** [comment]
Thanks @xeBuz!

**Comment by elliott-maguire** [comment]
Is there currently any other way to set the extension to default to the dark theme aside from being in Incognito? Would be nice to use just normally

**Comment by xeBuz** [comment]
@elliott-maguire I tried to make this part of a setting, but I failed miserable 😅 
That could be something to implement, I don't know how possible would be (I wasn't able to get the config on `src/utils/functions.js` nor `extension/resources/redirect.js`)

**Pull request merged**
